#!/usr/bin/env bash
# Target-side installer for a DockLite portable bundle (see scripts/pack-portable.sh).
# Run this from INSIDE an extracted bundle directory. It copies the prebuilt app
# and bundled Node runtime under ~/.local (no root, no build) and wires up the
# launcher, desktop entry and icon so DockLite appears in the app menu.
#
# ponytail: the launcher/desktop block below mirrors scripts/install-local.sh —
# keep the two in sync. Consolidate into a sourced helper if a third caller appears.
set -euo pipefail
umask 077

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -d "$HERE/app" ] && [ -x "$HERE/node/bin/node" ] \
  || { printf 'ERROR: run this from inside an extracted DockLite bundle (missing app/ or node/bin/node)\n' >&2; exit 1; }

SHARE_DIR="${DOCKLITE_INSTALL_ROOT:-$HOME/.local/share/docklite}"
APP_DIR="$SHARE_DIR/app"
DATA_DIR="$SHARE_DIR/data"
NODE_DIR="$SHARE_DIR/node"
BIN_PATH="$HOME/.local/bin/docklite"
DESKTOP_PATH="$HOME/.local/share/applications/docklite.desktop"
ICON_PATH="$HOME/.local/share/icons/hicolor/scalable/apps/docklite.svg"
PORT="${DOCKLITE_APP_PORT:-9010}"
URL="http://127.0.0.1:$PORT"
PID_FILE="$DATA_DIR/docklite.pid"

[[ "$PORT" =~ ^[0-9]+$ ]] && [ "$PORT" -ge 1 ] && [ "$PORT" -le 65535 ] \
  || { printf 'ERROR: DOCKLITE_APP_PORT must be a port number 1-65535 (got: %s)\n' "$PORT" >&2; exit 1; }

log() { printf '\n==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

installed_pid() {
  local pid
  [ -f "$PID_FILE" ] || return 1
  pid="$(cat "$PID_FILE" 2>/dev/null)" || return 1
  [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null || return 1
  tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null | grep -qF "$APP_DIR/server.cjs" || return 1
  printf '%s' "$pid"
}
port_listening() {
  (exec 3<>"/dev/tcp/127.0.0.1/$PORT") 2>/dev/null || return 1
  exec 3>&- 3<&-
  return 0
}

# --- verify the bundled runtime can load the native deps on THIS machine -----
log "Checking bundled runtime"
(cd "$HERE/app" && "$HERE/node/bin/node" -e 'require("argon2"); require("ssh2"); require("dockerode");') \
  || die "bundled native dependencies failed to load on this machine.
   The bundle was built for a different CPU arch or a newer glibc than this system has.
   Rebuild the bundle on (or for) this machine's platform."

# --- stop a running install, then swap in the new files ----------------------
WAS_RUNNING=0
if RUNNING_PID="$(installed_pid)"; then
  WAS_RUNNING=1
  log "Stopping running DockLite (pid $RUNNING_PID)"
  kill "$RUNNING_PID"
  for _ in $(seq 1 20); do kill -0 "$RUNNING_PID" 2>/dev/null || break; sleep 0.5; done
  kill -0 "$RUNNING_PID" 2>/dev/null && die "old server (pid $RUNNING_PID) did not stop"
elif port_listening; then
  die "port $PORT is in use by a process this installer does not manage; free it and re-run"
fi

log "Installing DockLite under $SHARE_DIR"
mkdir -p "$DATA_DIR" && chmod 700 "$DATA_DIR"

# Swap with rollback: if the copy is interrupted (disk full, Ctrl-C, error),
# restore the previous app+runtime so the launcher never points at a partial or
# mismatched install. The prior versions are held in .old until success.
SWAP_STARTED=0
rollback() {
  local rc=$?
  trap - EXIT
  if [ "$SWAP_STARTED" = 1 ] && [ "$rc" != 0 ]; then
    log "Install failed (exit $rc) — restoring previous version"
    rm -rf "$APP_DIR" "$NODE_DIR"
    [ -d "$APP_DIR.old" ] && mv "$APP_DIR.old" "$APP_DIR"
    [ -d "$NODE_DIR.old" ] && mv "$NODE_DIR.old" "$NODE_DIR"
  fi
  exit "$rc"
}
trap rollback EXIT

rm -rf "$APP_DIR.old" "$NODE_DIR.old"
SWAP_STARTED=1
[ -d "$APP_DIR" ] && mv "$APP_DIR" "$APP_DIR.old"
[ -d "$NODE_DIR" ] && mv "$NODE_DIR" "$NODE_DIR.old"
cp -r "$HERE/app" "$APP_DIR"
cp -r "$HERE/node" "$NODE_DIR"

NODE_BIN="$NODE_DIR/bin/node"

log "Installing launcher, icon, and desktop entry"
mkdir -p "$(dirname "$BIN_PATH")" "$(dirname "$DESKTOP_PATH")" "$(dirname "$ICON_PATH")"

APP_DIR_Q="$(printf '%q' "$APP_DIR")"
DATA_DIR_Q="$(printf '%q' "$DATA_DIR")"
URL_Q="$(printf '%q' "$URL")"
PID_FILE_Q="$(printf '%q' "$PID_FILE")"
NODE_BIN_Q="$(printf '%q' "$NODE_BIN")"
LOCK_FILE_Q="$(printf '%q' "$DATA_DIR/.launch.lock")"

cat > "$BIN_PATH" <<EOF
#!/usr/bin/env bash
# DockLite launcher (generated by scripts/install-portable.sh — do not edit by hand).
# NODE_BIN points at the runtime bundled alongside the app.
set -euo pipefail
umask 077
APP_DIR=$APP_DIR_Q
DATA_DIR=$DATA_DIR_Q
PORT=$PORT
URL=$URL_Q
PID_FILE=$PID_FILE_Q
NODE_BIN=$NODE_BIN_Q
LOCK_FILE=$LOCK_FILE_Q

installed_pid() {
  local pid
  [ -f "\$PID_FILE" ] || return 1
  pid="\$(cat "\$PID_FILE" 2>/dev/null)" || return 1
  [ -n "\$pid" ] && kill -0 "\$pid" 2>/dev/null || return 1
  tr '\0' ' ' < "/proc/\$pid/cmdline" 2>/dev/null | grep -qF "\$APP_DIR/server.cjs" || return 1
  printf '%s' "\$pid"
}

port_listening() {
  (exec 3<>"/dev/tcp/127.0.0.1/\$PORT") 2>/dev/null || return 1
  exec 3>&- 3<&-
  return 0
}

ensure_running() {
  mkdir -p "\$DATA_DIR" || { echo "cannot create \$DATA_DIR" >&2; return 1; }
  chmod 700 "\$DATA_DIR" || true
  # Serialize launches so a double-click can't spawn two servers that race on
  # the pidfile. The lock lives on fd 9 of a subshell, so it is released the
  # instant the check-and-start section ends — before any exec xdg-open, which
  # would otherwise inherit the fd and hold the lock for the browser's lifetime.
  (
    flock 9 || { echo "cannot acquire launch lock" >&2; exit 1; }

    installed_pid > /dev/null && exit 0
    if port_listening; then
      echo "Port \$PORT is in use by a process this launcher does not manage; refusing to start." >&2
      exit 1
    fi

    cd "\$APP_DIR" || { echo "cannot enter \$APP_DIR" >&2; exit 1; }
    # 9>&- closes the lock fd in the daemon: a long-lived server must not inherit
    # the flock, or it would hold the lock forever and deadlock later launches.
    DOCKLITE_REMOTE_ENABLED=1 DOCKLITE_HOST=127.0.0.1 DOCKLITE_PORT="\$PORT" \\
    DOCKLITE_AUTH_CONFIG_PATH="\$DATA_DIR/auth-config.json" \\
    DOCKLITE_ENGINE_TARGETS_PATH="\$DATA_DIR/engine-targets.json" \\
    nohup "\$NODE_BIN" "\$APP_DIR/server.cjs" >> "\$DATA_DIR/docklite.log" 2>&1 9>&- &
    echo \$! > "\$PID_FILE" || { echo "cannot write pidfile" >&2; exit 1; }

    for _ in \$(seq 1 40); do
      curl -fsm 2 "\$URL/api/health" > /dev/null 2>&1 && exit 0
      sleep 0.5
    done
    echo "DockLite failed to start; see \$DATA_DIR/docklite.log" >&2
    exit 1
  ) 9>"\$LOCK_FILE"
}

stop_server() {
  local pid
  if pid="\$(installed_pid)"; then
    kill "\$pid"
    for _ in \$(seq 1 20); do kill -0 "\$pid" 2>/dev/null || break; sleep 0.5; done
    if kill -0 "\$pid" 2>/dev/null; then
      echo "DockLite (pid \$pid) did not stop; leaving it managed" >&2
      return 1
    fi
    rm -f "\$PID_FILE"
    echo "DockLite stopped (pid \$pid)"
  else
    echo "DockLite is not running"
  fi
}

case "\${1:-open}" in
  stop)
    stop_server
    ;;
  start)
    ensure_running || exit 1
    ;;
  open)
    ensure_running || exit 1
    exec xdg-open "\$URL"
    ;;
  *)
    echo "usage: docklite [start|stop]" >&2
    exit 2
    ;;
esac
EOF
chmod 755 "$BIN_PATH"

cp "$HERE/docklite-icon.svg" "$ICON_PATH"
chmod 644 "$ICON_PATH"

# Icon is an absolute path (a user-local hicolor theme has no cache/index, so a
# bare "Icon=docklite" name would fall through to a generic icon). Exec is
# double-quoted so spaces/metachars in $HOME stay one argument; % is escaped as
# %%. Reject the handful of chars that would need fragile multi-stage escaping.
case "$BIN_PATH" in
  *\\*|*\"*|*\`*|*\$*|*[[:cntrl:]]*)
    die "launcher path contains a character unsupported in a .desktop Exec (\\ \" \` \$ or a control char): $BIN_PATH" ;;
esac
BIN_PATH_DESKTOP="${BIN_PATH//%/%%}"
cat > "$DESKTOP_PATH" <<EOF
[Desktop Entry]
Type=Application
Name=DockLite
Comment=Lightweight Docker UI
Exec="$BIN_PATH_DESKTOP"
Icon=$ICON_PATH
Terminal=false
Categories=Development;
Actions=Quit;

[Desktop Action Quit]
Name=Quit DockLite
Exec="$BIN_PATH_DESKTOP" stop
EOF
chmod 644 "$DESKTOP_PATH"

command -v update-desktop-database > /dev/null && update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true
command -v gtk-update-icon-cache > /dev/null && gtk-update-icon-cache -q "$HOME/.local/share/icons/hicolor" 2>/dev/null || true

if [ "$WAS_RUNNING" = 1 ]; then
  log "Restarting DockLite"
  "$BIN_PATH" start || log "start failed — launch it from the app menu once Docker is available"
fi

rm -rf "$APP_DIR.old" "$NODE_DIR.old"
log "Installed. Launch DockLite from your app menu, or run: $BIN_PATH"
printf '    (Requires Docker running and your user in the docker group.)\n'
